import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavbarComp from "@/components/NavbarComp";
import NavbarMobileComp from "@/components/NavbarMobileComp";
import FooterComp from "@/components/FooterComp";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Voyago",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <NavbarComp></NavbarComp>
        <NavbarMobileComp></NavbarMobileComp>
        {children}
        <FooterComp></FooterComp>
      </body>
    </html>
    
  );
}
